# Generated by Django 6.0.4 on 2026-04-25 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_changeorder_materialsubmittal_rfi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='current_level_index',
            field=models.IntegerField(default=0, help_text='Current approval level index (0-based)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='total_approval_levels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='municipal_reference',
            field=models.CharField(blank=True, help_text='Government reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approval_pin',
            field=models.CharField(blank=True, help_text='Hashed PIN for approvals', max_length=128),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('partially_approved', 'Partially Approved'), ('fully_approved', 'Fully Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('pm', 'Project Manager'), ('contractor', 'Contractor'), ('inspector', 'Inspector/Engineer'), ('consultant', 'Consultant/QS'), ('municipal', 'Municipal Inspector'), ('client', 'Client Representative'), ('reviewer', 'Reviewer')], default='contractor', max_length=20),
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_order', models.IntegerField()),
                ('level_name', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('seal_number', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='core.dailylog')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_order', models.IntegerField()),
                ('level_name', models.CharField(max_length=50)),
                ('required_role', models.CharField(blank=True, max_length=50)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('notification_emails', models.TextField(blank=True, help_text='Comma-separated emails')),
                ('timeout_hours', models.IntegerField(default=48, help_text='Hours before escalation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_levels', to='core.project')),
                ('required_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level_order'],
                'unique_together': {('project', 'level_order')},
            },
        ),
    ]
