# Generated by Django 4.2.11 on 2026-04-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailylog_current_level_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrecord',
            name='level_name',
            field=models.CharField(default='Approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='approvalrecord',
            name='level_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='current_level_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='status',
            field=models.CharField(choices=[('submitted', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='total_approval_levels',
            field=models.IntegerField(default=1),
        ),
    ]
