# Generated by Django 4.2.11 on 2026-04-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_approvalrecord_level_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrecord',
            name='level_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='approvalrecord',
            name='level_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='current_level_index',
            field=models.IntegerField(default=0, help_text='Current approval level index (0-based)'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('partially_approved', 'Partially Approved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='total_approval_levels',
            field=models.IntegerField(default=0),
        ),
    ]
